### PR TITLE
docs: update to style-guide links

### PR DESCRIPTION
**Pull request by Yonet**
Fixed links to John Papa style guide to new repo location.

### CODE REVIEW

**Comment by Yonet** [comment]
I signed it!

**Comment by luisvt** [comment]
I think your problem is that you committed without author parameter. You can amend your  commit with:

`git commit --amend --author="Author Name <email@address.com>"`

**Comment by Yonet** [comment]
Thank you @luisvt, amend worked.

**Comment by wardbell** [comment]
I like it! Merging

**Pull request closed without merging**
