### PR TITLE
docs(dart): redirect to webdev/angular

### PR DESCRIPTION
**Pull request by chalin**
cc @naomiblack @kevmoo @kwalrath

### CODE REVIEW

**Comment by kevmoo** [comment]
LGTM! I'd love to get this landed ASAP

**Comment by naomiblack** [comment]
@chalin is there also a PR removing dart doc generation from the build process to go with this one?

**Comment by chalin** [comment]
@naomiblack - yes there will be separate PRs (I haven't started work on adjusting the build scripts yet).

**Comment by chalin** [comment]
Contributes to #2930

**Comment by kevmoo** [comment]
It seems like this is landed now...did I miss something?

**Comment by chalin** [comment]
@kevmoo - I was just cross linking to the main tracker issue.

If this has indeed been merged, maybe @wardbell or @juleskremer can close this?

**Comment by naomiblack** [comment]
this is merged.

**Pull request closed without merging**
