### PR TITLE
Added my-app directive to the ES5 'Getting started' guide

### PR DESCRIPTION
**Pull request by SamVerschueren**
Fixes issue https://github.com/angular/angular.io/issues/94 by adding the `my-app` directive to the html.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
I signed it!

**Comment by kwalrath** [comment]
@davideast want to take a look?

**Comment by rkirov** [comment]
LGTM.

**Comment by kwalrath** [comment]
Thanks, @SamVerschueren and @rkirov!

**Pull request merged**
