### PR TITLE
fix typo in template-syntax.jade

### PR DESCRIPTION
**Pull request by ilyagelman**
directives*t* -> directives

### CODE REVIEW

**Comment by ilyagelman** [comment]
Signed.

**Comment by ilyagelman** [comment]
@wardbell Any particular reasons for declining typo fixes?

**Comment by wardbell** [comment]
I didn't decline it. I accepted it!  Our process rebases your contribution into the code base with a new commit and closes your PR.  That's what "wardbell closed this in 1d52d4b 7 days ago" means.

Sorry for the confusion about that. We ***value*** your help.

**Comment by ilyagelman** [comment]
@wardbell Sorry, didn't mean to sound in the wrong mood :-)

The process was just a bit misleading for me.

**Pull request closed without merging**
