### PR TITLE
docs(glossary): Fix ECMAScript description

### PR DESCRIPTION
**Pull request by trotyl**
ES2016(ES7) has already been officially published.

### CODE REVIEW

**Comment by wardbell** [comment]
Sorry but I cannot find evidence that ES 2016 has been ratified. I see _predictions_ that it will be ratified in June 2016 but maybe it didn't actually happen?

If I'm wrong, please send evidence.

**Comment by trotyl** [comment]
Why not have a look at official site? 

http://www.ecma-international.org/publications/standards/Ecma-262.htm

**Comment by trotyl** [comment]
Relevant announcement can been found in the official news(http://www.ecma-international.org/news/index.html):

> June 14, 2016	The 111th General Assembly held in Montreux, June 14, 2016, approved the following documents:
> 	
> ECMA-262 7th edition - ECMAScript® 2016 Language Specification
> ECMA-402 3rd edition - ECMAScript® 2016 Internationalization API Specification
> ECMA-413 1st edition - Data Migration Method for BD Recordable and BD Rewritable Disks
> ECMA-414 1st edition - ECMAScript® Specification Suite

**Comment by wardbell** [comment]
Thanks.  I looked but not the right place. Merging.

**Pull request closed without merging**
