### PR TITLE
fix some links in resources, update map to include the UK (oops)

### PR DESCRIPTION
**Pull request by ericjim**
### Preview
* https://angular-io-resources.firebaseapp.com/resources

@naomiblack @petebacondarwin

### CODE REVIEW

**Comment by Foxandxss** [comment]
Fix the frontend masters indentation while you are there

**Comment by ericjim** [comment]
@foxandxss woah, I didn't notice that.

**Comment by ericjim** [comment]
How's that @Foxandxss

**Comment by Foxandxss** [comment]
Sounds good to me 👍

**Comment by naomiblack** [comment]
merged and live!

**Pull request closed without merging**
