### PR TITLE
s/npmcdn/unpkg/g

### PR DESCRIPTION
**Pull request by mjackson**
[npmcdn.com](https://npmcdn.com) has officially moved to [https://unpkg.com](unpkg.com). This PR updates all URLs in your examples and docs.

### CODE REVIEW

**Comment by mjackson** [comment]
I signed it!

**Comment by robwormald** [comment]
LGTM 👍

**Comment by Foxandxss** [comment]
We should go with #2227 since it changes all the files.

**Comment by robwormald** [comment]
yeah, true.

**Comment by mjackson** [comment]
I missed some?

**Comment by Foxandxss** [comment]
Yes.

But thanks a bunch.

**Pull request closed without merging**
