### PR TITLE
docs(guide): add Dart intro

### PR DESCRIPTION
**Pull request by kwalrath**
@wardbell Here's my work in progress. We still need to get the examples ready, but I think the text is close. You can see the diffs between the TS & Dart versions here:

https://github.com/kwalrath/angular.io/commit/f0fa8e8ff180736fbd7a34b06004429362279b52#diff-d402be7e11ce92b900f4020006d7c80d

### CODE REVIEW

**Comment by kwalrath** [comment]
@tomplusplus when https://github.com/angular/angular.io/pull/448 is in (or at least when the docregions are in that PR) I'll update this PR to use the real Dart code.

**Comment by tomplusplus** [comment]
#448 is updated with the docregions

**Comment by kwalrath** [comment]
Great. Thanks!

**Comment by wardbell** [comment]
FWIW,  I recently split intro into intro and architecture. You may want to follow suit

**Comment by kwalrath** [comment]
Will do. Thanks for the heads up.

**Comment by kwalrath** [comment]
I'm going to commit this soon...

**Pull request closed without merging**
