### PR TITLE
docs(user input): copyedit TS user-input chapter

### PR DESCRIPTION
**Pull request by kwalrath**
Also fix print formatting to not print the sidenav.

### CODE REVIEW

**Comment by kwalrath** [comment]
@wardbell here's another copyedit, for you to review at your leisure. I'm now going to start converting the Dart version of the first chapter I edited (displaying-data).

**Comment by kwalrath** [comment]
@wardbell I'm going to start converting this to Dart. If we subsequently make any changes to the TS version before committing this, then I'll make them to the Dart version, as well.

**Comment by wardbell** [comment]
Dive right in!

**Comment by wardbell** [comment]
I like all your suggestions. Pushing them (after squasing).

N.B. We have to come back and change all "template *expressions*" to "template *statements*".

I'll do that in a subsequent PR.

**Pull request closed without merging**
