### PR TITLE
docs(toh-5): dashboard uses [routerLink] bindings #998

### PR DESCRIPTION
**Pull request by wardbell**
Per issue #998, switch from imperative routing to anchors with `[routerLink]` bindings in the `DashboardComponent`.

Kept the button-click imperative navigation in `HeroesComponent` mainly to show how to do that when you need imperative navigation but also because this use case is more button-like than anchor-like.

@chalin Modified the DART example to match. I _think_ I did it right but would be great if you confirmed.

### CODE REVIEW

**Comment by chalin** [comment]
googlebot, you are mistaken, I did author the commit.

**Comment by chalin** [comment]
I did author the commits. Googlebot!

**Comment by wardbell** [comment]
Thanks, @chalin. Merging. You'll come back latter with the Dart fixes and remove the entry from ` bad-code-excerpt-skip-patterns.txt`.

**Comment by chalin** [comment]
Follow-up is #2744.

**Pull request merged**
