### PR TITLE
Changed ToDoApp to show the actual remaining todos

### LINKED ISSUE #521: Incorrect remaining count in TodoApp example
To get the remaining count the get method should be

```typescript
get remaining(): number {
    return this.todos.reduce((count, todo: Todo) => count - todo.done, this.todos.length);
}
```

### PR DESCRIPTION
**Pull request by aksharpatel47**
Fixes #521

### CODE REVIEW

**Comment by petebacondarwin** [comment]
LGTM although it might be clearer to write:

```
return this.todos.length - this.todos.reduce((count, todo: Todo) => count + todo.done, 0);
```

**Comment by aksharpatel47** [comment]
@petebacondarwin That will show the done count and not the remaining count.

**Comment by wardbell** [comment]
I agree with @ntaoo; the method should do what it says its doing. I'd keep the `reduce`.  
```
  get remaining() : number {
    return this.todos.reduce((count, todo: Todo) => count + !todo.done, 0);
  }
```
No need for the explicit return type either; TS knows it's a number.

**Comment by petebacondarwin** [comment]
Actually I really like the filter version!

**Comment by wardbell** [comment]
@petebacondarwin why prefer filter to reduce? It's not a huge deal in practice but reduce is more to the point.

It is also more efficient because it does not create a new array, only to discard it after calculating its length (I repeat: not measurable in practice).

**Comment by petebacondarwin** [comment]
@wardbell well it just matches my brain's understanding of what we are trying to do. But on second look I am happy with your suggestion too.

**Comment by wardbell** [comment]
THE MOST IMPORTANT thing is that we fix the darned method soon ... because it presently returns the number of completed Todos rather than the number remaining.

With everyone's indulgence, I'm just going to git-er-done here.

**Comment by aksharpatel47** [comment]
@wardbell : You just wrote my thoughts during this entire conversation.

**Comment by petebacondarwin** [comment]
Indulge yourself, with post-yule fervour!

**Pull request closed without merging**
