### PR TITLE
docs(api/dart): avoid duplicate entries and fix breadcrumbs

### PR DESCRIPTION
**Pull request by chalin**
Currently two entries are generated for top-level library members like classes, and the main API page for these members has no-so-useful breadcrumbs. E.g., the main API page for `PipeMetadata` has breadcrumb: `angular2 > angular2 > PipeMetadata`, vs. the proper breadcrumb `angular2 > angular2.core > PipeMetadata` that appears on the second copy of the API page entry.

TLDR; within the `angular2` package there is a top-level catch-all library of the same name the exports most of the contained libraries. This results in duplicate API page entries (one for `angular2.foo` and one for `angular2.some_sub_lib_id.foo`). Furthermore, all internal page links to `foo` go to `angualr2.foo` so we loose breadcrumb information. This commit fixes the issue by hiding the top-level `angular2` library definition only for the purpose of running dartdoc.

### CODE REVIEW

**Comment by chalin** [comment]
@kwalrath @wardbell @Foxandxss : ready for review.

I also did a minor cleanup, removing superfluous parentheses in the language regex.

**Comment by chalin** [comment]
Travis doc build is green. The failure is due to the e2e toh-6 flake.

**Comment by kwalrath** [comment]
The doc builds, but I don't see a difference in the output, compared to what's on angular.io. What should I be look at/for?

**Comment by chalin** [comment]
Visit, say, [Pipes](https://angular.io/docs/dart/latest/api/angular2.core/Pipe-class.html), and then follow the `PipeMetadata` link in the Inheritance section.

**Comment by kwalrath** [comment]
Ah, OK. So those files are still being generated, but they aren't being linked to. Goodl

**Comment by chalin** [comment]
Yes.

Anything else to do before this is merged?

**Comment by kwalrath** [comment]
@wardbell or @Foxandxss does the code look good to you?

**Pull request merged**
