### PR TITLE
docs(quickstart): added system.js configuration to use 3rd party ng2 modules

### PR DESCRIPTION
**Pull request by valorkin**
Hi
All the time I am getting reports about same issue from different people
who tries to follow `5 min start guide` and system.js
`Uncaught SyntaxError: Unexpected token < `
So I have prepared appendix to your guide with sample how to
install 3rd party angular2 module and configure system.js to work with it propertly

If any changes is required just wrote

Thanks in advance

### CODE REVIEW

**Comment by valorkin** [comment]
@wardbell can you please take a look?

**Comment by wardbell** [comment]
I think this is valuable information but it does not belong in the quickstart.  We are not teaching how to add 3rd party modules to an A2 app in this chapter.

Thanks for your offer but I'm afraid we must refuse it.

**Comment by naomiblack** [comment]
Hi @valorkin -- Ward is right that this doesn't fit in the quickstart, but I am happy to see you have a module to share and we'll be working on a section about best practices for third party modules soon. Would you be interested in helping to write it?
cc @IgorMinar

**Comment by valorkin** [comment]
@naomiblack yeap, absolutely!

**Comment by IgorMinar** [comment]
Here is the outline for the chapter:
https://docs.google.com/document/d/1lomtiPzHhYzmg2PtifdIhJiL8p2JhO_txgbgbwGBBrA/edit

Writing just the portion on how to use 3rd party components would be a
great start.

**Comment by wardbell** [comment]
Agreed!  Having just written one I can confirm there is a lot of work involved.

I added a few more considerations:
* testing
* copyright, licensing, and open sourcing (source open) options
* how to prepare for contributions (assuming it is open sourced)

I would ***not** expect you (or anyone) to cover all of these topics in depth. But they deserve some coverage.

Should check with Google/A2 team about the legal issues mentioned and how they relate to what Google can or cannot do to promote a 3rd party component.

**Comment by IgorMinar** [comment]
Ward, feel free to add suggestions directly into the chapter outline doc.

**Comment by wardbell** [comment]
I did!  I copied them here :-)

**Comment by valorkin** [comment]
Does google doc supports forks and PRs or I should ask for edit access?:)

**Comment by IgorMinar** [comment]
ask for edit access

**Pull request closed without merging**
