### PR TITLE
(NgModule Guide) Change property name to align with other examples.

### LINKED ISSUE #2094: Property Inconsistency
angular modules ngmodule - ts - google chrome 11_08_2016 05_33_21 p m
As you can see the properties are inconsistent, in one file it is *user* and the other says *userName*.

### PR DESCRIPTION
**Pull request by Pablo-Ivan**
Changed property "userName" to "user" because in other files it is needed the property "user". Fixes #2094

### CODE REVIEW

**Comment by Foxandxss** [comment]
prose needs change

**Comment by Pablo-Ivan** [comment]
@Foxandxss How would I write it?

**Comment by Foxandxss** [comment]
Just change the references from `userName` to `user`.

**Comment by Pablo-Ivan** [comment]
Yes, I precisely did that. Or what do you mean? Sorry, English is not my native language.

**Comment by Foxandxss** [comment]
Necesitas cambiar el texto también, no solo el código. La guía vaya.

**Comment by Pablo-Ivan** [comment]
Ah, de acuerdo. Pero veo que en la guía ya está especificado como "user" en lugar de "userName".

**Comment by Foxandxss** [comment]
Cierto, aunque `userName` aparece varias veces en otros códigos. Creo que será mejor que cambies `user` por `userName` en `title.component` y cambies el texto.

---

True, but `userName` appears a couple of times in the other files. Will be better if you change `user` to `userName` in `title.component` and change the text.

**Comment by Pablo-Ivan** [comment]
Ah, yes...you're right. Ok, I will do it.

**Comment by wardbell** [comment]
Thanks. Your suggestion is incorporated in PR #2179

**Pull request closed without merging**
