### PR TITLE
Fixes OS/X deletion of non-essential files

### PR DESCRIPTION
**Pull request by leebenson**
Fixes the following error:

> xargs: illegal option -- a

### CODE REVIEW

**Comment by leebenson** [comment]
I signed it!

**Comment by trescenzi** [comment]
This seemingly doesn't solve the problem that it is intended to solve: angular/quickstart#369. The issue doesn't seem to be the command but the file being read itself. I've commented in the issue with more detail. If you'd like I can submit a PR against angular/quickstart that solves the problem.

**Comment by leebenson** [comment]
Thanks @trescenzi. Some extra thoughts [here](https://github.com/angular/quickstart/issues/369#issuecomment-276422284)

**Comment by wardbell** [comment]
Closed by https://github.com/angular/angular.io/commit/b2f41484721265026c87fb5c8780a8a4a57d5b61#diff-ea8e16eabf541f0e00287f1ba4bf7a69R79

**Pull request closed without merging**
