### PR TITLE
chore: move to provide object literal

### PR DESCRIPTION
**Pull request by Foxandxss**
I used the "provided object literal" to define this new syntax. We were using it already and I agreed with it.

I removed two examples from `dependency injection` and touched Dart prose and one of the files so please @chalin or @kwalrath confirm that I didn't break it.

Removing two examples the numbers jump from example 1 to example 3a, but that is just internal. I can fix the numbers if needed.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Seems like I left some behind, working on that.

**Comment by kwalrath** [comment]
I took a quick look; @chalin will take a closer one.

**Comment by chalin** [comment]
@Foxandxss : let me know once this is ready for review.

**Comment by Foxandxss** [comment]
I definitely broke the Dart part, but @chalin will fix it when this hit master.

**Comment by Foxandxss** [comment]
Also changed a blue box where it explains differences from Dart to Typescript in regard of provide. I changed the prose there, but feel free to change it too.

**Comment by wardbell** [comment]
Proceeding with the agreement that @chalin will fix what we broke in Dart at his convenience.

**Pull request closed without merging**
