### PR TITLE
DO NOT MERGE (mocks only): Api html templates

### PR DESCRIPTION
**Pull request by alexwolfe**
@IgorMinar @naomiblack @juleskremer 

## Description
This branch contains html templates for the new API doc pages. These templates are strictly html and use the sass/js currently used throughout the rest of the site. These templates should be used as a reference for structuring new elements. 

I've created a static html folder for these templates located at: 
`/public/templates/` 

## Known issues / expectations
- The content for the template (version numbers, code examples, etc.) may not be 100% up to date. The template is created with the goal of showcasing the new design and structure not for actual content use. 

## Viewing Template files 
Simply checkout out the repo and run the usual: `gulp serve-and-sync` then you can view the pages with the links below. 
- [API Component Decorator Example](http://localhost:3000/templates/api-component-decorator.html)
- [API ngIf Directive Example](http://localhost:3000/templates/api-ngif-directive.html)
- [API ngFor Directive Example](http://localhost:3000/templates/api-ngfor-directive.html)

### CODE REVIEW

**Comment by alexwolfe** [comment]
@IgorMinar Hmm, not seeing the Nexus 5 issue, I'm using chromes browser to test with the Nexus 5 setting. Can you send me a screen shot of what you're seeing? Attaching what I see currently: 
screen shot 2017-01-25 at 11 05 42 pm

**Comment by alexwolfe** [comment]
@IgorMinar Ok Just pushed an update to the branch. I've included an example of what the page should look like if the user clicks on the `...` button for the contributors. You can view the footer on the [ngFor Directive page](http://localhost:3000/templates/api-ngfor-directive.html) to see an example.

**Comment by IgorMinar** [comment]
@alexwolfe thanks for the changes. I can no longer repro the responsiveness issues for ngFor with the latest commit. I was still able to repro it before the commit, but it might have been a chrome dev tools bug. I think this PR is good.

I'll have my team take it from here and we'll contact you if we find any issues during the integration work to into the new app.

Thanks again.

**Comment by IgorMinar** [comment]
just to clarify - we are NOT going to merge this repo because we worked on just mocks. I'll keep this PR open until we copy all the contents over to angular/angular where the new app is being built.

**Comment by wardbell** [comment]
The design of the new aio pages is complete, rendering this PR moot.

**Pull request closed without merging**
