### PR TITLE
Avoiding Hero duplication

### PR DESCRIPTION
**Pull request by krzysiekpiasecki**
Prevent adding duplicates when '''enter''' and then '''blur''' events occured.

### CODE REVIEW

**Comment by krzysiekpiasecki** [comment]
I signed it!

**Comment by krzysiekpiasecki** [comment]
It;s about a duplication issue @googlebot

**Comment by Foxandxss** [comment]
Ohh the irony.

**Comment by wardbell** [comment]
Thanks for this change. But, believe it or not, I _intended_ for the duplication in the one case and not in the other. Because it is intended (which doesn't make it right, just intentional), I'm closing your PR. Thanks again.

**Pull request closed without merging**
