### PR TITLE
Suggested Corrections

### PR DESCRIPTION
**Pull request by imanabu**
Various clarifications and fixes as I was trying to go over the quoickstarts.

### CODE REVIEW

**Comment by imanabu** [comment]
I signed it!

**Comment by wardbell** [comment]
I like your suggestions. Unfortunately, there are small conflicts with a recently accepted update to this document. Will be happy to accept yours after you've reconciled.

**Comment by wardbell** [comment]
I believe that most if not all of these changes are obviated by newer versions of the docs.

If you believe any of them remain outstanding, please re-open and identify them ... and we'll take action.

Thanks for your help.

**Comment by imanabu** [comment]
Prefect, Ward. Thank you.

*Manabu Tokunaga   BIO <http://www.linkedin.com/in/manabu>*
*CEO*
tel/txt: (650) 762-8413 email . hangout: manabu@wingumd.com

<http://www.wingumd.com>
A Mobile Medical Collaborations & Communications Company
Palo Alto, California
[image: Download BodyMapSnap Today!]
<https://itunes.apple.com/us/app/bodymapsnap/id832815892?mt=8&ign-mpt=uo%3D4>

**Comment by imanabu** [comment]
Ward,

Why are you guys are so hell bent on not saying you need to

*sudo* npm install -g live-server

A good number of Mac users will have to do this. I know enough to know
that, but how about all the rest.


*Manabu Tokunaga   BIO <http://www.linkedin.com/in/manabu>*
*CEO*
tel/txt: (650) 762-8413 email . hangout: manabu@wingumd.com

<http://www.wingumd.com>
A Mobile Medical Collaborations & Communications Company
Palo Alto, California
[image: Download BodyMapSnap Today!]
<https://itunes.apple.com/us/app/bodymapsnap/id832815892?mt=8&ign-mpt=uo%3D4>

**Pull request closed without merging**
