### PR TITLE
(docs) gettingstarted: Update to alpha-37 and latest guidance

### PR DESCRIPTION
**Pull request by wardbell**
-- squashed commits (earliest to latest) --
(examples) gettingstarted: Update to alpha-37
(fix) gettingstarted: remove id=output from template; e2e spec looks for h1 instead
(fix) gettingstarted: simplified tsd commands
gettingStarted.jade updated for tooling-4
(docs) gettingstarted example revised for system 0.19, tsd 0.6.5, and as preface to ToH
(docs) update gettingstarted to our current recommendation (still needs to be vetted)
(docs) fix:gettingStarted.jade - small clarification after following instructions on clean directory.
(docs) gettingstarted jade updated w/ tool version advice and John's suggestions

### CODE REVIEW

**Comment by wardbell** [comment]
This is a pure update to Getting Started (TS) and does not rely on any tooling changes since dev-tooling-4

**Comment by naomiblack** [comment]
@wardbell could you please rebase on top of master? I just merged in Jay's PR and there are some conflicts with this one.

**Comment by wardbell** [comment]
Will do

**Comment by PascalPrecht** [comment]
@wardbell you don't have to close your PR. Just rebase on your local machine and force push to your branch, that will update this PR automatically :)

**Comment by wardbell** [comment]
That's what I wanted to do. I was thrown off course by an unexpected cascade of deleted files and panicked ;-)

**Pull request closed without merging**
