### PR TITLE
docs(ts): fix api url of Provider class

### PR DESCRIPTION
**Pull request by not-for-me**
Fix broken link of Provider class

### CODE REVIEW

**Comment by Foxandxss** [comment]
I need @chalin to validate that we should change _cache by hand or not.

**Comment by not-for-me** [comment]
@Foxandxss Yap! plz check to need change _cache by hand :)

**Comment by Foxandxss** [comment]
Could you please remove the changes to the _cache file? Thank you.

**Comment by not-for-me** [comment]
@Foxandxss rollback _cached file!

**Pull request closed without merging**
