### PR TITLE
docs(ugprade): bring phonecat upgrade tutorial up to speed with modernized Angular 1.x PhoneCat

### PR DESCRIPTION
**Pull request by teropa**
WIP - Do not merge until Tero says "go"

Relates to angular/angular-phonecat#326
Relates to angular/angular.js#14416

### CODE REVIEW

**Comment by naomiblack** [comment]
@teropa is this ready to merge?

**Comment by teropa** [comment]
@naomiblack Ideally we'd merge it around the same time with angular/angular.js#14416. @petebacondarwin what are your current plans for that?

**Comment by gkalpak** [comment]
It's better not to merge it yet. I'll ping you once angular/angular.js#14416 is merged (or ready to be merged).

**Comment by naomiblack** [comment]
Thanks for the clarification!

**Comment by wardbell** [comment]
@teropa  - how does this relate to the new world version?  My inclination is to stop dev here.

**Comment by teropa** [comment]
@wardbell This is now out of date. I'll need to rebase it.

**Comment by teropa** [comment]
@gkalpak We're now up-to-date with rc.1 and new world packacing here. Ready when you are! 😄

**Comment by teropa** [comment]
@gkalpak @petebacondarwin Would you mind if we land this on angular.io ahead of you? 

I'm off for vacation after next week and would like to get this and a few other changes to the ugprade guide in before that.

**Comment by petebacondarwin** [comment]
Just checking with @gkalpak - there may be a couple of small changes that need to be accommodated before we merge the tutorial PR. Will let you know before tomorrow

**Comment by gkalpak** [comment]
@teropa, the main PRs have landed. You are good to go :smiley:
A couple minor modifications might be necessary (e.g. we introduced `!` as the hash-prefix; see [this commit][1]). I could take care of these minor modifications to the upgrade guide after this is merged, if you want me to.

[1]: https://github.com/angular/angular.js/pull/14416/commits/d7be60fbfd577c1954d348bb56c2455cef98ae4d

**Comment by teropa** [comment]
@gkalpak Great, thanks! I'm working through some other changes to upgrade, so I can take care of the additional changes as well.

**Comment by teropa** [comment]
Closing this unmerged. The required changes are covered in #1538

**Pull request closed without merging**
