### PR TITLE
Wasn't any mention of `sub: any` in the heroes tour tutorial

### PR DESCRIPTION
**Pull request by SimonBiggs**
When I was going through the tutorial I noticed there wasn't any mention of `sub: any`.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
I signed it!

**Comment by Foxandxss** [comment]
This needs rebase my friend.

**Comment by wardbell** [comment]
I can't find `sub: any` in that file or ANY file in `angular.io`

**Comment by SimonBiggs** [comment]
Sorry about that. I made this pull request while I was doing the tutorial during rc4. I found a bit that didn't flow and found it was due to this. I think the docs have changed a bit since then.

**Pull request closed without merging**
