### PR TITLE
Fixes for breaking changes in Jade v1.0.0, closes #60

### LINKED ISSUE #60: resolve issues with harp 17
David ran into issues here -- need to investigate

### PR DESCRIPTION
**Pull request by kennethormandy**
Hey! These changes should close issue #60.

After a lot of waiting, we finally updated Jade in Harp to v1.x. There were breaking changes that we did our best to mitigate, but unfortunately one particular you were using a lot happened to have its syntax changed.

Now, Jade makes you reference variables like this:

```jade
- var myTitle = 'Hello, world.';
```

If you’re interested, we have a blog post on the changes here: http://harpjs.com/blog/v0-17-0

Anyway—major breaking preprocessor changes like this aren’t a regular occurrence, and we do our best to limit the impact as much as possible. Sorry if it caused you any trouble.

[Review on Reviewable](https://reviewable.io/reviews/angular/angular.io/96)

### CODE REVIEW

**Comment by kennethormandy** [comment]
I signed it!

**Comment by kwalrath** [comment]
@kennethormandy I see your email in the CLA signers but not your GitHub username. Which means that we can accept your changes once @alexwolfe says they're good, but the CLA bot might continue to complain.

**Comment by kennethormandy** [comment]
@kwalrath I’m not sure I understand, but okay, thanks! Let me know if there is something I can do make it easier.

**Comment by kwalrath** [comment]
The bot works in mysterious ways, but it seems happy now. Now just waiting on @alexwolfe to OK this change.

**Comment by alexwolfe** [comment]
Thanks @kennethormandy really appreciate these changes. Can  you remove the changes to the /api pages. Those pages are auto generated and will be blown away every we update. I'll update the API pages in the other repo so that it generates these updates.

**Comment by kennethormandy** [comment]
Hey @alexwolfe not sure if this is still something that you want fixed up? I can try and rebase this PR if this is still an issue.

**Comment by kennethormandy** [comment]
Alright, not sure what happened there…I tried to rebase against master and it doesn’t look like it worked quite as I expected. Let me know, I can always open a new PR if that is easier.

**Comment by naomiblack** [comment]
thank you! some of our files are generated, so I had to address this in the templates, but we are up-to-date now and running on harp 0.17.0.

**Pull request closed without merging**
