### PR TITLE
Wolfe banner

### PR DESCRIPTION
**Pull request by alexwolfe**
@naomiblack The initial work is done, still need to add a dot navigation (for switching slides). I have two announcements in there right now, let me know if there is another I should add in this PR. thanks.

### CODE REVIEW

**Comment by alexwolfe** [comment]
I signed it!

**Comment by ericjim** [comment]
A note for me and @chalin. We will need to port this over.

**Comment by alexwolfe** [comment]
@ericjim @naomiblack Ok this one should be all set. Ready to be reviewed and merged.

**Comment by alexwolfe** [comment]
@naomiblack also signed the CLA so not sure what else I need to do get that warning to go away? maybe donate some blood 😂

**Comment by ericjim** [comment]
Works for me.

**Comment by alexwolfe** [comment]
I signed it!

**Comment by naomiblack** [comment]
merged, live

**Pull request closed without merging**
