### PR TITLE
[WIP] Rebase for final edits

### PR DESCRIPTION
**Pull request by cfranger**
This PR supercedes PR #2685.
@wardbell @naomiblack I have some technical as well as editing questions with my changes here, all starting with "CF:" Who is best to sync up with?

### CODE REVIEW

**Comment by naomiblack** [comment]
@robwormald should be able to take a look on Friday, if you guys want to find a time to sync up.

**Comment by cfranger** [comment]
Thanks, @naomiblack and @robwormald. I'll get in touch with Rob to figure out a time to meet.

**Comment by wardbell** [comment]
I will resolve the conflicts and give quick review.

**Comment by wardbell** [comment]
Moved to a new PR #3077 under IdeaBlade repo (that's where we authors do our work so everyone can share and commit to the same PR).

#3077 closes this PR.

**Pull request closed without merging**
