### PR TITLE
Dev tooling2

### PR DESCRIPTION
**Pull request by jtraband**
Added support for fragment styling via regexp for makeTabs and makeExample
Added gulp help support
Added gulp task to determine which examples and associated jade files are affected as a result of a given git commit.
... and associated refactoring and cleanup.

### CODE REVIEW

**Comment by btford** [comment]
Wow! @jtraband and @wardbell, you two have been going to town!

It'd be great if we could split these kinds of PRs up into a couple smaller ones, and maybe do some squashing next time.

Taking a look now.

**Comment by btford** [comment]
> Files changed 382

I'm kinda overwhelmed. Even ignoring the generated fragments, I'm having a hard time following this. @jtraband: are there a couple key files/modifications that you could point me towards?

**Comment by wardbell** [comment]
I'm going to get rid of 272 unwanted file changes and squash this thing today.

We've wanted to do smaller PRs but its been hard to get the cycle going fast enough. We'll work on this for the next round.

Meanwhile, hang tight on this PR. We're likely to withdraw it and submit something less ominous.

Please note that, post squash, the commit message will likely be crisp such as: " updated dev guide sample code management infrastructure and getting started samples"

**Comment by btford** [comment]
:+1: Thanks, Ward

**Comment by wardbell** [comment]
Close and discard this PR in favor of #203

**Pull request closed without merging**
