### PR TITLE
docs(readme): fix local doc browsersync

### LINKED ISSUE #344: Browser is not reloaded on all local file changes
While running `serve-and-sync`, changing `public\docs\ts\latest\tutorial\toh-pt1.jade` will trigger a `browserSync` to reload the page, accompanied by a `[BS] File changed: public\docs\ts\latest\tutorial\toh-pt1.jade` message on the console.

However, changing `public\docs\ts\latest\quickstart.jade` doesn't either reload nor present a console message.

The culprit seems to be this glob in the browserSync tasks: `files: ["public/docs/**/*/**/*" ]`.

### PR DESCRIPTION
**Pull request by filipesilva**
Close #344

### CODE REVIEW

**Comment by wardbell** [comment]
Checking with Jay (when he gets back).

**Comment by petebacondarwin** [comment]
I think that #369 is a bit tighter.

**Comment by petebacondarwin** [comment]
Fixed via #369

**Comment by filipesilva** [comment]
Agree :+1:

**Pull request closed without merging**
