### PR TITLE
api-builder: update to dgeni-packages 0.12.0 - factoring out the typescript package

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Comment by wardbell** [comment]
What's holding this up?

**Comment by petebacondarwin** [comment]
@wardbell I was waiting for someone to review before I unilaterally merged it.

**Comment by petebacondarwin** [comment]
But happy to do so, if you can verify that the site looks correct to you after gulping it

**Comment by wardbell** [comment]
Merged in 8b1683f51397e704363c52ec504331a60a0fa43e and two previous commits

**Pull request closed without merging**
