### PR TITLE
docs(resources): adds resources by thoughtram

### PR DESCRIPTION
**Pull request by PascalPrecht**
These articles are kept constantly up-to-date

### CODE REVIEW

**Comment by PascalPrecht** [comment]
I've updated the PR with another article we've published a day ago. Do you think this can be merged?

**Comment by PascalPrecht** [comment]
Pinging @naomiblack :)

**Comment by PascalPrecht** [comment]
Uhm.. anyone fancy at least reviewing it? :D

**Comment by PascalPrecht** [comment]
Updated and rebased.

**Comment by fvanwijk** [comment]
Are there any policies on what resources should be in this list?
Currently the list consists of posts by Victor (official Angular dev) and Angular conference material (also official).

I have no doubt about the quality of your articles, however since you're quite active and other bloggers may be not, this list could become a Thoughram-only one.
Other contributors (bloggers) may cover the same subjects and may have the same quality level.
Perhaps first add the most valuable Thoughtram links to keep the list a bit less unskewed?

**Comment by PascalPrecht** [comment]
> Are there any policies on what resources should be in this list?

Not that I know of.

> Currently the list consists of posts by Victor (official Angular dev) and Angular conference material (also official).

Well, the blog posts listed in the resources are still his private blog

> I have no doubt about the quality of your articles, however since you're quite active and other bloggers may be not, this list could become a Thoughram-only one.

Currently it's a Victor only one, which I'm trying to fix :)

> Other contributors (bloggers) may cover the same subjects and may have the same quality level.

No doubt!

> Perhaps first add the most valuable Thoughtram links to keep the list a bit less unskewed?

This is what the PR is all about.

**Comment by PascalPrecht** [comment]
However, I do understand if this ends up to be too thoughtram-y. Maybe this list is not even needed anymore, since we put more energy into the official docs lately anyways.

Would love to hear what @naomiblack thinks. I could also update the PR to only link to http://blog.thoughtram.io/exploring-angular-2

**Comment by wardbell** [comment]
Pascal - Please get in touch with me to discuss if this PR is still viable or should be closed.

**Pull request closed without merging**
