### PR TITLE
chore(gulp): avoid watching tmp files

### PR DESCRIPTION
**Pull request by chalin**

### CODE REVIEW

**Comment by chalin** [comment]
@Foxandxss : very minor change is ready for review and merge.

**Comment by Foxandxss** [comment]
What is that globbing going to filter?

**Comment by chalin** [comment]
Temporary files generated by Emacs during editing.

**Comment by chalin** [comment]
Actually, I don't think that we should be watching _any_ dot files, but in particular not autosave files. Maybe that line can be changed simply to `**/.?*`. Let me know what you prefer.

**Comment by chalin** [comment]
FYI, I changed it to `**/.?*`.

**Comment by chalin** [comment]
Actually, this still isn't solving my original problem (of getting browser page refreshes when Emacs does an auto-file backup). So I'll close this for now.

**Pull request closed without merging**
