### PR TITLE
fix(docs): Renamed files for JavaScript/Dart dynamic form cookbook

### PR DESCRIPTION
**Pull request by brandonroberts**
Fixes issue with white page being displayed when switch to JavaScript/Dart on the dynamic form cookbook page. Also fixes the menu item to match.

cc: @wardbell @naomiblack

### CODE REVIEW

**Comment by Foxandxss** [comment]
Is not the first time that this happens and won't be the last one. Perhaps we should look for a different solution altogether.

**Comment by wardbell** [comment]
I'm confused. I thought the topic was "Dynamic Forms" (plural). "Dynamic Form" (singular) sounds weird. What was the problem?

**Comment by brandonroberts** [comment]
Yes, the topic is "Dynamic Forms" (plural). If you switch to viewing the JavaScript version of "Dynamic Forms" the cookbook menu item displays "Dynamic Form" (singular)

**Comment by wardbell** [comment]
um ... OK.  I think I understand. Let's move on.

**Pull request closed without merging**
