### PR TITLE
docs: misc fixes in user input

### LINKED ISSUE #159: Small fixes in Step By Step Guide User input - js
Hi, 
First of all thanks for the tutorial. 
When I was trying the final code (typescript) on the following url https://angular.io/docs/js/latest/guide/user-input.html.
I noticed some small bugs in the code.
- NgIf is not used in the code but it is imported.
- Typo on Line 18:  NIf needs to either be removed or replaced by NgIf
- Typo on Line 10: *ngfor needs to be replaced by *ng-for

I will try to make a pull request later this week

### PR DESCRIPTION
**Pull request by vicb**
fixes #159 

supersedes #161 (This PR as the same content in a single commit)

### CODE REVIEW

**Comment by vicb** [comment]
CLA's ok

**Comment by vicb** [comment]
@kwalrath @naomiblack could one of you please merge this PR ? We've had 10+ bug reports for this

**Comment by kwalrath** [comment]
@naomiblack is out, but this seems safe enough, so I'll merge it and attempt to republish.

**Comment by vicb** [comment]
Thanks !

**Comment by kwalrath** [comment]
The fix is up! Please let me know if you notice anything that went wrong with the updated site. (I had to delete an extra lesson: #196.)

**Pull request merged**
