### PR TITLE
chore(gulp): except for check-deploy, gulp targets are for (ts|js) only

### PR DESCRIPTION
**Pull request by chalin**
As before, by default, the various gulp tasks will be for all languages. To skip Dart API doc generation and running E2E tests use the `--no-dart` flag.

### CODE REVIEW

**Comment by chalin** [comment]
@Foxandxss @wardbell : ready for review and merge.
@almerosteyn: this should fix it.

cc @kwalrath

**Comment by Foxandxss** [comment]
I like but I don't feel confortable having to put the  `--no-dart` in all my commands. Shouldn't it be otherwise? `--dart` or something like that. There is only 2 people in here that does dart and we have a l10n project to localize this project and all of them needs to run this command too and none of them really care about dart.

**Comment by chalin** [comment]
I agree and debated that myself. I'm just worried that it is much easier to forget to put `--dart` when generating docs (and get no warning) than to forget `--no-dart` in other case (which _will_ result in a friendly reminder being generated).

@naomiblack, @kwalrath : any opinion about this?

**Comment by wardbell** [comment]
I thought the default was no-dart except for check-deploy

**Comment by chalin** [comment]
As per @wardbell's suggestion (made elsewhere) I'll make `all` the default for full-site build tasks (like  `check-deploy`) and `(ts|js)` all other gulp targets.

**Pull request closed without merging**
