### PR TITLE
教程中的index.html的js引入是相对路劲,在不是根目录下的路由页面刷新会导致js无法找到而报错

### PR DESCRIPTION
**Pull request by chengtongtong**

### CODE REVIEW

**Comment by asnowwolf** [comment]
I've already talked with him and got the point. 

The steps is here:
1. Download Source Code from https://www.angular.io/resources/live-examples/toh-5/ts/plnkr.html to his local folder.
2. Serve the local folder via tsc and a web server.
3. Click a hero, and then the URL changed to http://localhost:81/detail/12.
4. Refresh the browser
5. It's 404 page

So, he modified the system.config.js and add a root path, It's resolved.

He is not confident of his English and feels sorry for writing this PR with Chinese.

**Comment by asnowwolf** [comment]
BTW: the Plunker is using some CDN js which was blocked by China GFW. So we have to download the examples to local folder and try it.

**Comment by asnowwolf** [comment]
He has signed the CLA, But here is still labeled by "CLA: no", what's the happen?
image

Or just take it as an issue, and fix it.

**Comment by Foxandxss** [comment]
@wardbell this PR is pretty much a mess. Close?

**Pull request closed without merging**
