### PR TITLE
Formatting - Back Quote to Wrap Identifier

### PR DESCRIPTION
**Pull request by mattezell**
"...builds a tree of `ActivatedRoute`s,..." should be "...builds a tree of `ActivatedRoutes`,..."

### CODE REVIEW

**Comment by mattezell** [comment]
I signed it!

**Comment by kwalrath** [comment]
We don't want to imply that the type name is `ActivatedRoutes`, so this change won't work, as is.

But you're right that "`ActivatedRoute`s" is not great.

How about "`ActivatedRoute` objects"?

**Comment by wardbell** [comment]
@kwalrath Exactly!  I'll fix it as I merge it

**Comment by mattezell** [comment]
Wow. Thanks, @wardbell...(?) Maybe you'll catch it 4 days earlier next time...

**Comment by mattezell** [comment]
Ha! Thanks, @kwalrath - you're right... I completely overlooked that before hitting submit :) 'ActiveRoute' not 'ActiveRoutes'.. Rookie mistake.  Glad it got sorted.

**Pull request closed without merging**
