### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by FintanK**
Keywords for package.json

### CODE REVIEW

**Comment by FintanK** [comment]
I signed it!

**Comment by Foxandxss** [comment]
We are not releasing this repo as a package so I don't think that keywords are needed.

**Comment by FintanK** [comment]
Not needed as such but metadata is never a bad idea in my opinion.

**Comment by wardbell** [comment]
Thanks for your effort and kind intent. Sorry to disagree though. 

A lack of keywords is not "bad metadata" or they wouldn't be optional.

There's nothing wrong with this contribution per se, so we may merge it.

**Pull request closed without merging**
