### PR TITLE
Update route docs to version 7 & fix linting issues (closes #1691)

### PR DESCRIPTION
**Pull request by iamarcel**
I took the liberty to fix the linting issues form #1691, @brandonroberts' PR.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Yes, but this duplicates his PR again instead of fixing the concrete error.

If you don't mind, I am going to close this and let him fix it. I need the authors to be able to lint their solutions too.

**Comment by Foxandxss** [comment]
Oh and thanks tho, I like the initiative like this, but would be problematic to merge if both PRs contain the same changes but a bit of difference.

**Comment by iamarcel** [comment]
Sure, no problem! I thought it looked like a bit of a mess already ;)
I'll send my PR to Brandons' fork (so that my hard 3 minutes' work isn't wasted, right? :stuck_out_tongue_winking_eye:).

**Comment by Foxandxss** [comment]
That wouldn't do any good, so instead of 3 mins, it would be 5 :P

Let him fix the lint errors. I want each author here to get used to lint their solutions.

**Comment by iamarcel** [comment]
Dammit! But you've definitely got a point. I'll wait until the day I can fix my own linting issues then ;)

**Pull request closed without merging**
