### PR TITLE
docs(quickstart): post-RC5 Dart resync

### PR DESCRIPTION
**Pull request by chalin**
- Resync Dart QS prose with TS, post RC5.
- Added to-be-shared Jade `var` definitions to `_util-fns.jade`.
- Delete cached QS jade file.
- Eliminate the stub file `styles.1.css` in favor of a `docregion` in the main `styles.css`.

This commit requires a `gulp add-example-boilerplate` after pulling it in.
Contributes to #2077.

### CODE REVIEW

**Comment by chalin** [comment]
@Foxandxss @wardbell @kwalrath : as usual, it is best to view the [diff while ignoring whitespace](https://github.com/angular/angular.io/pull/2078/files?w=1).

**Comment by kwalrath** [comment]
Comparing http://localhost:3000/docs/dart/latest/quickstart.html & https://angular.io/docs/dart/latest/quickstart.html side-by-side, I see an extra paragraph in the new one (the circled `<my-app>` in the screenshot).

hqfhejjkcyr

**Comment by kwalrath** [comment]
Aside from that one thing, which you could fix later, LGTM.

**Comment by chalin** [comment]
Yes, I had chosen to leave it out earlier, but since it is actually a target (#my-app), I figured that it made sense to include the "heading".

**Comment by kwalrath** [comment]
Merging now...

**Comment by chalin** [comment]
For the record, the `<my-app>` heading was removed (reverting to how things were before).

**Pull request merged**
