### PR TITLE
Rc5 doc sweep

### PR DESCRIPTION
**Pull request by johnpapa**
Removed 03-05, 04-12, 04-15.  …
Removed style for whitespace in imports.

Removed + sign prefix for routing folders. Updated all code.

Removed style that said to use lazy loading.  There was no value in the style other than use it :)

### CODE REVIEW

**Comment by Foxandxss** [comment]
Sounds good to me. Did you delete also the examples folders? (and routes...)

**Comment by johnpapa** [comment]
I removed the folders for the examples (where there were ones). I also renamed the examples folders without the `+` and the code that points to them. 

Of course, please check :)

**Comment by Foxandxss** [comment]
Weird, this only shows me that you deleted 03-05 (not 04-12 nor 04-15)

**Comment by johnpapa** [comment]
there is no 04-12. i just removed 04-15

**Comment by johnpapa** [comment]
hmmm. I don't see a 04-12 or 04-15 in the examples

**Comment by Foxandxss** [comment]
That is what you said in the first comment! :P

**Comment by Foxandxss** [comment]
Oh, we have styles without example, forgot :P

**Comment by johnpapa** [comment]
@wardbell this is ready for you

**Pull request merged**
