### PR TITLE
fix(quickstart): add issue link for traceur

### PR DESCRIPTION
**Pull request by elmariofredo**
I'm not sure if this is proper way, but surely users should know why they need to include traceur-runtime in Angular 2 project.

[Review on Reviewable](https://reviewable.io/reviews/angular/angular.io/146)

### CODE REVIEW

**Comment by kwalrath** [comment]
@davideast could you take a look? This might overlap with some other bugs/PRs.

**Comment by alexeagle** [comment]
The traceur issue has been moved to https://github.com/angular/angular/issues/2829
I'm not sure whether we should tell users this or if it's TMI

**Comment by elmariofredo** [comment]
Hi,

I don't think it's TMI, as every step of quickstart should be explained to make experimenting user confident of what and why he is doing and traceur along with typescript is in my opinion raising eyebrows.

I have updated link, but decision is up to you.

**Comment by wardbell** [comment]
Closing because this document has been completely rewritten and your changes no longer apply. But many thanks for engaging and contributing. We need that!

**Comment by elmariofredo** [comment]
no problem, I'm glad that there is no raised eyebrow moment any more :wink:

**Pull request closed without merging**
