### PR TITLE
#38: Add an optional data-file attribute to display file names in header

### PR DESCRIPTION
**Pull request by gorork**
Hey @kwalrath, how about this?
For an example, see the first code section in `http://localhost:9000/docs/dart/latest/guide/displaying-data.html`

To display a corresponding file name/path pass an optional attribute **data-file**, like this: 
```
data-file="web/main.dart"
``` 
Check my changes in `displaying-data.jade` to see all that is required for adding file names.

[Review on Reviewable](https://reviewable.io/reviews/angular/angular.io/116)

### CODE REVIEW

**Comment by alexwolfe** [comment]
@gorork I'm making some significant changes to the code boxes, I have a branch out to turn them into directives. I'll add the title attribute into that branch for this meta data.

**Comment by gorork** [comment]
@alexwolfe Yes, directive looks reasonable for these code boxes. Could you self-assign this and all the related issues, since they're already under development?

**Comment by alexwolfe** [comment]
@gorork Yes, really sorry about that.

**Comment by kwalrath** [comment]
I just saw these, and I'm really looking forward to them going in. Thanks for your work, @gorork!

**Comment by gorork** [comment]
@kwalrath Glad it can help! :)
Actually, if merged, you could start adding file names to code boxes right away and use it until new directive is ready.

**Comment by alexwolfe** [comment]
@gorork sorry unfortunately it would create more work for me to undo in my branch. I'm going to leave this for now and then when my changes are merge in, I'll see if I can roll your branch in.

**Comment by gorork** [comment]
@alexwolfe Ok, let me know if you need me to edit this pr to fit your changes.

**Comment by wardbell** [comment]
Closing because this document is being completely rewritten based on the new TS version.

Many thanks for your engagement and contribution. We need that!

**Pull request closed without merging**
