### PR TITLE
[WIP] docs(guide/template-syntax): create Dart version

### PR DESCRIPTION
**Pull request by kwalrath**
So far, I've only worked on the sample.

### CODE REVIEW

**Comment by kwalrath** [comment]
I've saved my work on the Dart text here, but it's not ready for review yet.

**Comment by kwalrath** [comment]
Now it's ready for review, though not ready to be published. Please pay special attention to "QUESTION:" and "Dart difference:".

**Comment by kwalrath** [comment]
@wardbell you might want to check out how I did the includes. Do they look reasonable to you?

**Comment by wardbell** [comment]
@kwalrath LGTM. I pinged Jay again about moving the `_.` files to a subfolder. That's a must!

I like your naming convention ... starting a new #docregion prefix at each section break. That should work everywhere.

Looking at your Dart file, my sense is that this is a workable approach. Thanks to your convention, I can find my way between the two versions pretty easily.

How does it feel to you?

When can we accept this?  I have some pending updates to this chapter (#818 new `ngSwitch` and `ngForTrackBy` syntax)  that await at least the TS version of the jade.

**Comment by kwalrath** [comment]
My approach seem pretty workable. I think this page was an extreme example, since it's so long, but it was pretty easy to know where I was when I needed to make a fix.

I'm hoping to clear up the remaining questions within the next couple of days.

**Comment by kwalrath** [comment]
The TS version is ready to go, but the Dart content still needs review, so I've moved it to template-syntax-NEW.jade.

I'm going to commit this PR, and I'll finish/publish the Dart version in a separate PR.

**Comment by kwalrath** [comment]
The draft Dart content is viewable at https://angular.io/docs/dart/latest/guide/template-syntax-NEW.html.

**Pull request closed without merging**
