### PR TITLE
docs(toh-5/dart): use routerLink in dashboard

### LINKED ISSUE #2775: [Dart] follow-up to #2718 - docs(toh-5): dashboard uses [routerLink] bindings
Work on this has started, see #2744.

We're awaiting feedback from @matanlurey concerning a possible issue with routerLink.

cc @kwalrath

### PR DESCRIPTION
**Pull request by chalin**
Fixes #2775
Contributes to #998

### CODE REVIEW

**Comment by chalin** [comment]
As agreed with @kwalrath, here is the updated prose and code, with a mention of https://github.com/dart-lang/angular2/issues/186.

**Comment by chalin** [comment]
@wardbell @filipesilva @Foxandxss - minor updates were made to the TS .jade file, see [changes here, ignoring whitespace](https://github.com/angular/angular.io/pull/2744/commits/c32800b2d8c32a6f7ddcb45e2f48d10c62d92257?w=1).

**Comment by filipesilva** [comment]
@chalin looks fine to me for the TS changes. The removal of the docregion terminator in `public/docs/_examples/toh-5/ts/app/dashboard.component.ts` doesn't seem to do anything though, but it also doesn't break anything.

**Comment by chalin** [comment]
@filipesilva - right, doc regions are automatically closed at the end of file; so explicitly naming them is unnecessary. Thanks for the review!

**Pull request merged**
