### PR TITLE
fix: boost transparency of sidenav

### PR DESCRIPTION
**Pull request by ericjim**
Fixes: https://github.com/angular/angular.io/issues/2408

### Preview
screen shot 2016-09-20 at 8 55 39 pm

cc @chalin

### CODE REVIEW

**Comment by alexwolfe** [comment]
Believe it or not it will actually reduce the contrast ratio (since bg color will be a darker gray). So for accessibility, the color is better at .56. 

Any specific reason to change it (preference is a valid option btw :) )

**Comment by ericjim** [comment]
The reason for change was to fix: https://github.com/angular/angular.io/issues/2408, though I get what you mean with the contrast ratio, it's really subtle.

**Comment by alexwolfe** [comment]
@ericjim Ahhh, good catch. Can you simply apply it to the mobiles styles? Otherwise I can do it today (will be tinkering around today anyway). Let me know.

**Comment by ericjim** [comment]
@alexwolfe How's that?

**Comment by alexwolfe** [comment]
@ericjim perfect 👍 Thanks for fixing this!

**Pull request merged**
