### PR TITLE
chore: add lint instructions to readme

### PR DESCRIPTION
**Pull request by Foxandxss**
We need to tell others that before creating a PR, they should lint their example.

### CODE REVIEW

**Comment by Foxandxss** [comment]
While at it, I am going to debug travis again.

**Comment by Foxandxss** [comment]
I saw that variable hack on protractor's repo and seems to work fine here.

I vote for merge it and test it a few days.

/cc @filipesilva

**Comment by filipesilva** [comment]
The e2e fix looks good, this should help loads.

For the record, here is further information about the problem:
- https://github.com/angular/protractor/issues/2419#issuecomment-156527809
- https://github.com/angular/protractor/issues/2419#issuecomment-213112857

**Comment by naomiblack** [comment]
merged and live

**Pull request closed without merging**
