### PR TITLE
[SPIKE] docs: add real quickstart example DO NOT MERGE

### PR DESCRIPTION
**Pull request by Foxandxss**
**DO NOT MERGE, THIS IS ONLY A DEMO TO SEE HOW THIS IDEA WOULD LOOKS LIKE**

Don't mind the prose, it is practically copy & paste from the quickstart. The idea in here is to see how a quickstart tutorial with embedded plunkers look like.

### CODE REVIEW

**Comment by wardbell** [comment]
I don't think it should be sorted under introduction. So I kept it in position and re-titled: "Webpack: an introduction".

**Comment by Foxandxss** [comment]
Wrong PR :P

**Comment by wardbell** [comment]
Oops.

**Comment by Foxandxss** [comment]
Closing this. We can still check it closed and we can do a better demo with the new tooling too.

**Pull request closed without merging**
