### PR TITLE
New cheatsheet item syntax

### PR DESCRIPTION
**Pull request by petebacondarwin**
This PR builds on top of #457. It changes the syntax to the one discussed between @naomiblack  and @kwalrath

### CODE REVIEW

**Comment by naomiblack** [comment]
this is still not working for me.

I see this on Dart:
screen shot 2015-12-08 at 5 35 00 pm

**Comment by naomiblack** [comment]
I pushed this to master, but not to the live site. I'm fairly sure this is right and just missing content...

**Comment by petebacondarwin** [comment]
Did you run `gulp build-dart-cheatsheet`?

**Comment by petebacondarwin** [comment]
Closing as this has landed on master. I have created a new PR to update the cheatsheet docs themselves to this new syntax: https://github.com/angular/angular/pull/5733

**Pull request closed without merging**
