### PR TITLE
docs(js/guide): don't use shredder & _data.json fixes

### PR DESCRIPTION
**Pull request by chalin**
Also:
- synced `_data.json` with TS counterpart
- fixed some missed “Angular 2” -> “Angular” renamings (contributes to #2407)

### CODE REVIEW

**Comment by chalin** [comment]
Work in support of ng2.io.
cc @ericjim

**Comment by Foxandxss** [comment]
I don't dislike the changes but perhaps @wardbell wants to take a look at your changes in the _data.json

**Comment by wardbell** [comment]
This was merged some time ago.

**Comment by wardbell** [comment]
Oops. I guess not. Revived in PR #2467

**Pull request closed without merging**
