### PR TITLE
chore: devguide image compression

### PR DESCRIPTION
**Pull request by chalin**
Backport from Dart docs site of TS relevant images.

Fixes https://github.com/angular/angular.io/issues/2436

Courtesy of @kevmoo
cc @kwalrath

### CODE REVIEW

**Comment by wardbell** [comment]
Why are we backporting images? What do they have that the current images lack? What's up?

I can't tell what's different between the images nor what this PR is about.

Blocking while we await answers.

**Comment by kevmoo** [comment]
@wardbell github should show file sizes – these are a lot smaller 😄

**Comment by chalin** [comment]
Images are the same, just with smaller file sizes. Something that Naomi asked be done a while back (https://github.com/angular/angular.io/issues/2436).

**Comment by wardbell** [comment]
I didn't see significant size changes in the handful I checked. A few 100 bytes here and there.  And I didn't have time inspect the images that github wouldn't diff.  

I'm accepting your word (Patrice and Kevin) that this will all be fine.

**Pull request merged**
