### PR TITLE
todo app remaining tasks reducer func fixed and clarified

### PR DESCRIPTION
**Pull request by sulmanen**
Reduce func in get remaining() looked funny in the example. Maybe this is clearer.

### CODE REVIEW

**Comment by sulmanen** [comment]
I signed it!

**Comment by gkalpak** [comment]
Indeed `count + +!todo.done` was a little too much :)
Even simpler would be:

```js
this.todos.filter((todo: Todo) => !todo.done).length
```

**Comment by sulmanen** [comment]
why yes, much better.

**Comment by wardbell** [comment]
I agree that it reads better. The `reduce` would be more efficient if we had a gazillion todos ... an absurdity in itself. Accepting ... after taking it the last step (because of type inference):
```
return this.todos.filter(todo => !todo.done).length;
```

**Pull request closed without merging**
