### PR TITLE
docs(toh-5): add import example

### PR DESCRIPTION
**Pull request by kevinsearle**
Included sample of dashboard component import for consistency.

### CODE REVIEW

**Comment by chalin** [comment]
Hi Keven. Each tutorial part is filled with details specific to that part. In order to keep the text focused, we'll sometimes omit showing the details of some elementary step. For example, by the someone reaches part 5 of the tutorial, they should be well equipped to know how write an import statement without having to be shown the exact text.

I'd vote to note make this addition. @wardbell @Foxandxss ?

**Comment by kevinsearle** [comment]
Makes sense, however, for your consideration I would like to point out that while actually taking this tutorial for the first time this section tripped me up for a second due to this detail being included in previous tutorial chapters.

**Comment by chalin** [comment]
Thanks for the feedback Kevin.

Taking a peek at the live example sources is an option. Might that have been enough to help?

**Comment by kevinsearle** [comment]
That is what I did, however, I was thinking of future tutorial readers. I'll leave it in your hands to merge or not!

**Comment by wardbell** [comment]
I feel your pain. We are about to scrub the tutorial and rewrite parts of it that will affect this section. I believe in our rework we will be much more careful to show the steps we talk about (such as imports ... a problem for some here and elsewhere) while removing some of the other repetitive stuff. For that reason only, I'm closing this PR.  Please bear with us while we are in transition.

**Pull request closed without merging**
