### PR TITLE
test(e2e/dart): enable Basics chapter e2e testing

### PR DESCRIPTION
**Pull request by chalin**
Addresses #1522 in part.

### CODE REVIEW

**Comment by chalin** [comment]
@kwalrath, @thso : ready for review and merge.

**Comment by kwalrath** [comment]
I see "no changes" to those 4 files, for some reason.

**Comment by chalin** [comment]
@kwalrath : it is because they are just empty files; their presence enables the e2e tests.

**Comment by kwalrath** [comment]
I'm not sure what the protocol is when the CI build fails... @naomiblack? @wardbell?

**Comment by chalin** [comment]
@kwalrath : as far as I understand, the travis build is still under development. In fact the build is failing because of the build setup. So I believe that this failure is safe to ignore until Travis CI is officially supported.

**Comment by wardbell** [comment]
I didn't know that we HAD a travis build. I knew we were working on it.

Regardless, this LGTM

**Comment by kwalrath** [comment]
Cool, merging now...

**Pull request merged**
