### PR TITLE
docs(style-guide): add the image width attribute

### PR DESCRIPTION
**Pull request by not-for-me**
Adding the width attribute to the gif image of visual studio extension for supporting mobile phones.

### CODE REVIEW

**Comment by wardbell** [comment]
Why? Why is it a problem for this image and not every image in the docs?

**Comment by not-for-me** [comment]
@wardbell because every other image's width is smaller than mobile screen size, but the size of this image is bigger than 700px.
I think that the "%" width attribute of it for supporting mobile is need.

Thanks.

**Comment by johnpapa** [comment]
LGTM

**Comment by wardbell** [comment]
Thanks. Merged.

**Pull request closed without merging**
