### PR TITLE
res.json().data doesn't work

### PR DESCRIPTION
**Pull request by steinsag**
I tried it locally in a slightly different context, but I could never get any result with

    res.json().data

But if I replace it with

    res.json()

everything works fine.

### CODE REVIEW

**Comment by steinsag** [comment]
I signed it!

**Comment by wardbell** [comment]
What does "*I tried it locally in a slightly different context*" mean? What context is that?

The only context that matter w/r/t the `HeroService` is the chapter sample itself. I'm sorry but your claim of error and your proposed changes are simply not correct. 

The HTTP Chapter code works as demonstrated by the [plunker link](https://angular.io/resources/live-examples/server-communication/ts/plnkr.html) in the chapter itself. That plunker is generated directly from the sample

You can see that the `HeroService` code really is
```
  getHeroes () {
    return this.http.get(this._heroesUrl)
                    .map(res => <Hero[]> res.json().data)
                    .do(data => console.log(data)) // eyeball results in the console
                    .catch(this.handleError);
  }
```
If I had to guess, I'd say that you were targeting your own web api which returns response data in a different shape ... perhaps a response that lacks the wrapper object with a `data` property that *this* sample presupposes.

The chapter warns several times that you have to adjust to the actual characteristics of your API.

I'm closing until you can provide evidence that the chapter and sample are actually wrong.

**Comment by steinsag** [comment]
Ok, now I see. The sample data is wrapped in a 'data' key. Mmmh, surprising and not really needed. When reading the chapter I thought I always have to call json().data so that data is not referring to the structure of the returned json.

So any reason why you got this data thing in the sample data? Why not just have:

`[
    { "id": "1", "name": "Windstorm" },
    { "id": "2", "name": "Bombasto" },
    { "id": "3", "name": "Magneta" },
    { "id": "4", "name": "Tornado" }
  ]`

**Comment by PascalPrecht** [comment]
> Mmmh, surprising and not really needed. 

This is because returning `[]` directly from a JSON/REST endpoint is not valid JSON.

In other words, if you wanna be RESTful, this is needed.

**Comment by steinsag** [comment]
> This is because returning `[]` directly from a JSON/REST endpoint is not valid JSON.

That's not true, see: http://stackoverflow.com/a/5034547

**Comment by wardbell** [comment]
It's *valid* JSON. The problem is that it is ***insecure*** JSON on the wire.

See this [OWASP security guideline](https://www.owasp.org/index.php/OWASP_AJAX_Security_Guidelines#Always_return_JSON_with_an_Object_on_the_outside) on the subject

**Comment by PascalPrecht** [comment]
Right, sorry my statement was misleading. Security is the reason. Also, see this SO post: http://stackoverflow.com/questions/3503102/what-are-top-level-json-arrays-and-why-are-they-a-security-risk

**Comment by wardbell** [comment]
@steinsag Sorry for the confusion. It is easy to overlook the `data` property on the response in the sample API.

The real take-away should be: **look closely at the details of your web api *before* unpacking the result object**.

I tried to make that point. It doesn't always register.

**Pull request closed without merging**
