### PR TITLE
chore(install): fix install scripts & improve local usage

### PR DESCRIPTION
**Pull request by chalin**
Fix a few minor problems with Travis install & build scripts.
Other changes allow `before-install.sh` to be run locally.

### CODE REVIEW

**Comment by chalin** [comment]
@wardbell @Foxandxss : ready for review and merge.
cc @kwalrath

**Comment by kwalrath** [comment]
@filipesilva could you review this?

**Comment by filipesilva** [comment]
LGTM, @chalin thanks for making the scripts more compatible with local envs!

**Comment by kwalrath** [comment]
Thanks, Filipe! Merging now...

**Pull request merged**
