### PR TITLE
Pipe Doc Updates, clarification on impure pipes.

### PR DESCRIPTION
**Pull request by joeeames**

### CODE REVIEW

**Comment by wardbell** [comment]
Todos:

- [ ] Why A2 ships without a  `FilterPipe`
- [ ] Memoization in an impure pipe improves perf (that's what the crazy JSON example does)
- [ ] Trim some of the rhetorical excess (says the man with rhetorical excess)

**Comment by joeeames** [comment]
I believe the json example isn't actually memoized. it just executes once and then never executes again. memoization would involve a cache of inputs and corresponding outputs that shortcircuit the algorithm, but it doesn't do that.

RE the rhetorical excess: it definitely needs that.

**Comment by wardbell** [comment]
So am I a "go" to incorporate these changes into the chapter (w/ my usual filter)?

**Comment by joeeames** [comment]
yes

**Comment by wardbell** [comment]
moved to PR #974 where I can work on it

**Pull request closed without merging**
