### PR TITLE
chore: add forms package

### PR DESCRIPTION
**Pull request by filipesilva**
This PR adds the new `@angular/forms` package to angular.io examples.

/cc @Foxandxss

### CODE REVIEW

**Comment by Foxandxss** [comment]
And after we propagate this to all examples, no one cries?

**Comment by filipesilva** [comment]
Tried ToH-6 and it was fine.

**Comment by Foxandxss** [comment]
ToH, the ultimate _example where we can try everything.

It is good for me then.

**Comment by filipesilva** [comment]
I'll wait for the router update to do that as well.

**Comment by filipesilva** [comment]
Added in the router, but we need to check tests. I expect some of them to fail.

**Comment by filipesilva** [comment]
Unsurprisingly, `public/docs/_examples/router/ts` failed - but it was the only one, which is good.

@Foxandxss do we have an update in the works?

**Comment by Foxandxss** [comment]
What kind of update?

**Comment by filipesilva** [comment]
Blocked by https://github.com/angular/angular.io/pull/1691

**Comment by naomiblack** [comment]
merged and live!

**Pull request closed without merging**
