### PR TITLE
docs(toh): update live example links

### PR DESCRIPTION
**Pull request by chalin**
Addresses #1596.

### CODE REVIEW

**Comment by chalin** [comment]
@kwalrath @Foxandxss @wardbell : minor update ready for review.

**Comment by Foxandxss** [comment]
Sounds good, my only complain is... why Link2? What happened with link1? :P

**Comment by chalin** [comment]
:) ... Link2 actually generates 2 links in Dart.

**Comment by kwalrath** [comment]
I didn't try building it, but it LGTM. (More examples, yay!)

**Comment by chalin** [comment]
Anything else to do before this is merged?

**Comment by kwalrath** [comment]
I'm going to merge this now.

**Pull request merged**
