### PR TITLE
docs(aio):URL to DatePipe in Glossary

### PR DESCRIPTION
**Pull request by aravindfz**

### CODE REVIEW

**Comment by aravindfz** [comment]
Why was this PR closed?

**Comment by Foxandxss** [comment]
Did you read the warning when you tried to create it?

**Comment by aravindfz** [comment]
No I didn't read it. But help me out a new contributor

**Comment by Foxandxss** [comment]
You can start by reading it. Then we can move to the next step :)

**Comment by aravindfz** [comment]
Shall I raise another PR

**Comment by Foxandxss** [comment]
Yes, following the steps written in there :)

**Comment by aravindfz** [comment]
Yes, got it. wrong repository correct me if I m wrong again .. Created a new PR https://github.com/angular/angular/pull/16437

**Pull request closed without merging**
