### PR TITLE
docs(style-guide): push main.ts to src folder

### LINKED ISSUE #1361: StyleGuide - Having the root /app folder export a barrel
The CLI has a barrel in `/src/app` where they export the app.component.ts and some environment. Also the `main.ts` is at `/src` and not `/src/app`.

So we have to move `main.ts` up one level and then see if we want the `app` folder to export a barrel and if so, what should it export, only app.component or each subfolder (features and shared).

### PR DESCRIPTION
**Pull request by Foxandxss**
/cc @johnpapa  @wardbell  @Brocco @mgechev

We agreed on pushing `main.ts` to the src folder so here it is. We also talked about adding a barrel in `/src/app/` with a single export, but that is a no-no for @wardbell.

So with this PR and Ward's opinion, we can close the next issue:

Closes #1361

### CODE REVIEW

**Comment by johnpapa** [comment]
Cool. Has CLI adjusted too?

**Comment by Foxandxss** [comment]
CLI was always having main.ts in `src/`.

About the barrel, they export more than one thing, so that is fine for now I guess.

**Comment by mgechev** [comment]
LGTM

**Comment by wardbell** [comment]
The move is OK with me. As @Foxandxss says, I am intolerant of a barrel at the root with only `AppComponent` in it.

**Pull request closed without merging**
