### PR TITLE
doc(upgrade): grammatical fix. removed duplicate word 'our'

### PR DESCRIPTION
**Pull request by souvikbasu**

### CODE REVIEW

**Comment by souvikbasu** [comment]
I signed the CLA

**Comment by souvikbasu** [comment]
Hi, the pull request was closed without merging. Is this not a valid fix? Please let me know

**Comment by Foxandxss** [comment]
You just didn't read the warning when creating a new pull request :)

**Comment by souvikbasu** [comment]
Oh I am sorry, this was my first pull request so I am new to this. Do I have to create an issue first for this? Please let me know the correct way to do this

**Comment by souvikbasu** [comment]
Ah my bad. I guess I have submitted to the wrong repository which is deprecated now. I will submit a pull request to angular repo. Thanks for pointing now the mistake

**Pull request closed without merging**
