### PR TITLE
fix(quickstart): add angular2 typing file to tsc command

### PR DESCRIPTION
**Pull request by fjavierjimenez**
[Review on Reviewable](https://reviewable.io/reviews/angular/angular.io/123)

### CODE REVIEW

**Comment by fjavierjimenez** [comment]
I'm the author of the commit but with different email.

**Comment by alexwolfe** [comment]
@fjavierjimenez you'll need to merge forward and also sign the CLA. Thanks.

**Comment by fjavierjimenez** [comment]
signed and merged.

**Comment by alexeagle** [comment]
This change has backslashes which don't work for everyone.
What's more, I don't think this is needed because the quickstart instructs you to point the compiler at the typings with
```
/// <reference path="typings/angular2/angular2.d.ts" />
```
at the top of app.ts.
Can you verify if that fixes it for you?

**Comment by alexeagle** [comment]
pls re-open if I've gotten it wrong.

**Pull request closed without merging**
