### PR TITLE
docs(guide/attribute-directives): follow-up to #1654

### PR DESCRIPTION
**Pull request by chalin**
Mainly Dart-side review, following #1654:
- Updated Dart code to match TS.
- Ran dartfmt.
- Enabled e2e tests (#1523); suites passed:
  - public/docs/_examples/attribute-directives/dart
  - public/docs/_examples/attribute-directives/ts
- Prose copyedits.

### CODE REVIEW

**Comment by chalin** [comment]
@kwalrath @Foxandxss : ready for review.

**Comment by Foxandxss** [comment]
I just have one question which I put on a comment.

**Comment by kwalrath** [comment]
LGTM, but I didn't try to run the example or build-and-compare the Dart page. Would you like me to do either of those, @chalin?

**Comment by chalin** [comment]
I ran the tests (as mentioned in the initial comment), but you are welcome to confirm the results; here is the command to run from the angular.io repo root:
```
gulp run-e2e-tests --fast --lang=all --filter=attribute-directives
```
Do we have a `build-and-compare` target somewhere?

**Pull request merged**
