### PR TITLE
Update package.webpack.json

### PR DESCRIPTION
**Pull request by jgatjens**
Missing reflect-metadata module on package.json.

### CODE REVIEW

**Comment by jgatjens** [comment]
I signed it!

**Comment by Foxandxss** [comment]
Is not really missing, we are not using it in the example.

**Comment by jgatjens** [comment]
if you try to run the test you will get the an error.

**Comment by Foxandxss** [comment]
That is right. I will ask and then change it on test or revert the core-js.

**Comment by Foxandxss** [comment]
This got fixed.

**Pull request closed without merging**
