### PR TITLE
api-builder: replace underscores from jade filenames

### LINKED ISSUE #2184: [TS] API entry missing for http._createDefaultCookieXSRFStrategy
Visit https://angular.io/docs/ts/latest/api/http/index/ and click on the link to `_createDefaultCookieXSRFStrategy` which is found towards the end of the page. Result: 404, page not found.

The relevant code excerpt from `modules/@angular/http/http.ts` is:
```
/**
 * @experimental
 */
export function _createDefaultCookieXSRFStrategy() {
  return new CookieXSRFStrategy();
}
```
Notice that the function is exported.

Is the page for this entry being skipped because of the leading underscore? If so, then it should not appear in the index summary.

@ericjim @petebacondarwin 
cc @Foxandxss @kwalrath 

This is one of the broken links reported in #2150. (There is also a similar issue with `platform-browser/index/_WORKER_UI_PLATFORM_PROVIDERS-let.html`, but let's see how this issue is resolved first).

### PR DESCRIPTION
**Pull request by petebacondarwin**
Closes #2184

### CODE REVIEW

**Comment by chalin** [comment]
Ah, nice and simple fix. Maybe it would be better, though, to replace only the first leading underscore with a minus? Although unlikely, this could avoid potential clashes between an entry for `__foo` and `_foo`.

LGTM (though I haven't tried it).

**Comment by chalin** [comment]
cc @Foxandxss

**Comment by petebacondarwin** [comment]
I fixed it up to replace each leading '_' with the same number of leading '-'

**Comment by wardbell** [comment]
Please follow up with the Angular team. They should **not** be exporting public API members with leading underscore. Therefore, this appears to be a solution looking for a non-existent problem.

**Comment by petebacondarwin** [comment]
Although it is an "experimental" export so perhaps they wanted it to look a "bit private".

**Comment by petebacondarwin** [comment]
I think we should probably close this one now (@chalin?) given that @IgorMinar closed the original issue.

**Comment by chalin** [comment]
Yes, that's fine.

**Pull request closed without merging**
