### PR TITLE
adds filterable API list

### PR DESCRIPTION
**Pull request by robertmesserle**
@naomiblack Curious what you think of this iteration.  Note: the existing data does not have any entries for `directive` - they are all classified as `class`

### CODE REVIEW

**Comment by robertmesserle** [comment]
image

Including a screenshot

**Comment by naomiblack** [comment]
I really want to highlight the directives. Can we do anything manual to mark them up? there's not that many of them

**Comment by robertmesserle** [comment]
@naomiblack Yea, I was just giving a heads up that at this point, it doesn't have any directives in the data, nor do the URL's reflect Directives.

**Comment by mhevery** [comment]
Look for `@Directive` annotation, which tells you that it is a directive.

**Comment by naomiblack** [comment]
Here is a list of all the directives:
 CORE_DIRECTIVES: NgClass, NgFor, NgIf, NgStyle, NgSwitch, NgSwitchWhen, NgSwitchDefault

FORM_DIRECTIVES: NgControlName, NgControlGroup, NgFormControl, NgModel, NgFormModel, NgForm, NgSelectOption, DefaultValueAccessor, NumberValueAccessor, CheckboxControlValueAccessor, SelectControlValueAccessor, NgControlStatus, RequiredValidator, MinLengthValidator, MaxLengthValidator

**Comment by robertmesserle** [comment]
Updated screenshot:

image

**Comment by naomiblack** [comment]
Instead of "Templating" headers should match left nav headings (and include those terms). Note that Lifecycle Hooks are actually duplicated in core. It's fine to just remove them from core.
The icons don't all have text at center. Look at "D" and "V"

**Pull request closed without merging**
