### PR TITLE
Hack to make "{{ }}" can be correctly shown

### PR DESCRIPTION
**Pull request by peterwang1996**

### CODE REVIEW

**Comment by peterwang1996** [comment]
yeah, I signed it.

**Comment by filipesilva** [comment]
IIRC @petebacondarwin fixed this for `<code>` blocks in https://github.com/angular/angular.io/commit/7fb34523aefd88acf8502a510893f0c477d7119b

**Comment by peterwang1996** [comment]
Okay, and is that mean we have use `<code>` to contain things like `{{something}}`?

**Comment by filipesilva** [comment]
Correct, yes.

**Comment by wardbell** [comment]
Closing as this has been taken care of by  @petebacondarwin in 7fb3452 . Thanks for your help though!

**Pull request closed without merging**
