### PR TITLE
Update quickstart to use TypeScript

### PR DESCRIPTION
**Pull request by alexeagle**
This is ready to go, using a pre-release of typescript 1.5 beta from Mohamed's fork.
Note that we should re-publish this when the beta is released.

### CODE REVIEW

**Comment by alexeagle** [comment]
+ @davideast

**Comment by alexwolfe** [comment]
@kwalrath can you review and merge?

**Comment by alexeagle** [comment]
@naomiblack

**Comment by kwalrath** [comment]
Sorry, I didn't see this until now, @alexwolfe. I can review the writing, but someone else should do a technical review.

**Comment by naomiblack** [comment]
@kwalrath we're going to push this live later today -- let me know if you are mid-review on the writing, otherwise we might update after the push. (Would prefer before, but lmk!)

**Pull request merged**
