### PR TITLE
Dart update to alpha.45

### PR DESCRIPTION
**Pull request by tomplusplus**
@kwalrath. Updated dart examples to alpha.45

### CODE REVIEW

**Comment by kwalrath** [comment]
LGTM. Thanks!

You've confirmed that the samples still work? (I can't remember if there were any breaking changes between 39 & 45.)

**Comment by tomplusplus** [comment]
I didn't check the examples that were solely in the .jade files. I figured Since I was going to move that code out to _examples folder, I would check it then.

**Comment by kwalrath** [comment]
OK, that makes sense. So you'll remove the WIP when that's complete?

**Comment by tomplusplus** [comment]
@kwalrath That works for me. I was planning on creating a separate branch and PR for that. When its done I'll remove WIP.

**Comment by kevmoo** [comment]
@tomplusplus I confirmed everything runs. Woo hoo!

Would you rebase your commits on top of master – and make them one commit.

...and remove the [WIP] – I think this is ready to land!

**Comment by tomplusplus** [comment]
@kevmoo, I rebased with master ( when I say master though I'm talking the master of my fork. is that right?) I squashed the commits together and removed WIP.

Thanks :)

**Comment by kevmoo** [comment]
@tomplusplus Actually, rebase to origin

so

```console
> git fetch
> git rebase origin/master
```

Or

```console
> git checkout master
> git pull
> git checkout my_working_branch
> git rebase master
```

**Comment by kevmoo** [comment]
Although it merges cleanly, so I think we're good.

LGTM, as we say

@wardbell Do you do the honors?

**Comment by kwalrath** [comment]
I'll do the honors, but I think we might still need @wardbell or @naomiblack to update the site.

**Comment by kevmoo** [comment]
@kwalrath it looks like they avoid merges on angular.io – would love to see their suggested workflow...

**Pull request merged**
