### PR TITLE
fix: fix broken anchors

### PR DESCRIPTION
**Pull request by filipesilva**
Fixes https://github.com/angular/angular.io/issues/2359.

/cc @alexwolfe @naomiblack @wardbell @petebacondarwin

### CODE REVIEW

**Comment by alexwolfe** [comment]
Looks good, not sure why this is the fix? Seems brittle at best but great job finding the problem!

**Comment by filipesilva** [comment]
@alexwolfe you removed the directive from `.main-nav` in https://github.com/angular/angular.io/commit/65db6b9268310d4811a5d37069aa1e59489183e7#diff-5ae88e3969f17f6262fb230f79708071

It controls scrolling: https://github.com/angular/angular.io/blob/master/public/resources/js/directives/scroll-y-offset-element.js

There might be a better way to get scrolling to work though, atm I just wanted to restore the previous behaviour. 

I tried disabling A1 
```
$locationProvider.html5Mode({
  enabled: false,
});
```

**Comment by filipesilva** [comment]
Closed via e56bae4a8c71930c8112a744bf464553c99961e3

**Comment by petebacondarwin** [comment]
LGTM

**Pull request closed without merging**
