### PR TITLE
Fix 'angular2/angular2' imports to 'angular2/core'

### PR DESCRIPTION
**Pull request by twcrone**
Minor fix to example code imports

### CODE REVIEW

**Comment by twcrone** [comment]
I signed it!

**Comment by wardbell** [comment]
Thanks but, sadly, you've invested your time in hidden, unpublished pages that no one should reach. Some of them have no business being on the web at all.

The only exception is the testing page which is stuck in Angular alpha world and is scheduled for a complete overhaul. There is no value in "fixing it" either.

Appreciate the effort and very sorry to have lured you into this. But we won't be able to do anything with your PR.

In future, please focus on published pages. We'd love to accept your contributions.

**Comment by twcrone** [comment]
Ok, sorry.  I saw the minor issue on one page and I did a Find/Replace.  Pretty new to this so sorry for wasting your time.  This is the first JS UI framework I've really been interested in so I hope to be able to help not hinder.  Take care!

**Comment by wardbell** [comment]
No problem. We welcome help!  I'm sorry we wasted your by leaving this for you to find.

**Pull request closed without merging**
