### PR TITLE
docs(router): Removed references to deprecated router

### PR DESCRIPTION
**Pull request by brandonroberts**

### CODE REVIEW

**Comment by Foxandxss** [comment]
I like what I see Brandon.

You need to rebase because the style-guide change is already in master (I did it personally because I created that example).

The only remaining thing is the upgrade guide that I will tackle myself too.

**Comment by brandonroberts** [comment]
I've rebased against latest. I had a failed build due to animations but not related to my changes

**Comment by Foxandxss** [comment]
Animation is a different issue. I will fix it separately.

**Comment by brandonroberts** [comment]
This one is ready @Foxandxss . It removes all references to the deprecated router with the exception of testing and ngUpgrade.

**Comment by wardbell** [comment]
Also renames the constant variables to lowerCamelCase (as it should).
Merged.

**Pull request closed without merging**
