### PR TITLE
Fix decorator docs

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Comment by naomiblack** [comment]
We are going to hold this one until later in the week. @IgorMinar says not urgent.

**Comment by petebacondarwin** [comment]
Rebased and fixed up testing

**Comment by naomiblack** [comment]
@IgorMinar is this one ready to merge? I'm not sure what it should look like in output -- not sure how to tell if it's done.

**Comment by petebacondarwin** [comment]
Rebasing and looking into a potential Travis error.

**Comment by petebacondarwin** [comment]
@wardbell I accidentally caused this to close from a commit message in angular/angular. You might want to reopen this.

**Pull request closed without merging**
