### PR TITLE
docs(upgrade): PhoneCat upgrade tutorial

### PR DESCRIPTION
**Pull request by teropa**
For review - ping @wardbell and @PascalPrecht :)

Feel free to suggest all kinds of changes. I'm feeling particularly uncertain about the role Angular 1 TypeScript/TSD material, and would appreciate input on that.

The examples directories contain full, runnable copies of the PhoneCat app and are thus quite large.

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Huge! Will have a look now.

**Comment by PascalPrecht** [comment]
Uhm.. just realised that the PR says that `upgrade.jade` doesn't have any changes?

**Comment by teropa** [comment]
Hmm.. I think it's just GitHub UI giving up because of all that big PhoneCat stuff. Clicking through shows the new content

**Comment by teropa** [comment]
Wrong repo, closing!

**Pull request closed without merging**
